### ISSUE TITLE
Game crashes while trying to render a blank sandwich

### ISSUE THREAD

**Issue by Neubulae** [FoundationGames/Sandwichable#17]
How to reproduce:
1.Decides to give yourself a sandwich table thru commands
2.Accidentally gave yourself a sandwich
3.???
4.Profit

**Comment by FoundationGames** [comment]
Sandwiches with null tags render as barriers. From some of your other bug reports, I kinda get the feeling that you are using a mod that somehow applies nbt tags to all items, and it's causing NPEs because the correct tags are null. I'll leave this issue open because that IS my bad for not checking which NBT tags are not null. Thanks for the bug testing!
