### ISSUE TITLE
[Feature Request] Retain tags from sandwich ingredients

### ISSUE THREAD

**Issue by seylerius** [FoundationGames/Sandwichable#36]
Mods like Origins allow for restrictions on a player can eat. These restrictions depend on tags added to individual foods to determine what is and is not meat. Such tags are not retained when making a sandwich, however. A sandwich containing a steak is edible by a player with a vegetarian origin, while a steak on its own is not. Adding the meat tag to bacon, or any of the other sliced meats produced by Sandwichable, would be nice, but is easily resolved with a datapack.

**Comment by FoundationGames** [comment]
Likely the case is that a steak sandwich will be eaten by a vegetarian, but the steak won't actually restore any hunger. This is a compatibility issue that needs to be fixed by Origins, if at all. The meat tag part should be an easy fix on my end, though.

**Comment by seylerius** [comment]
Yeah, as long as you have some way of collecting and preserving ingredient tags or exposing the IDs of ingredients, the rest can be done with compatibility datapacks or an addition in Origins. I haven't taken a look to see what options, if any, you have in place for that, yet.

**Comment by FoundationGames** [comment]
Every single bit of data is conserved when an item is added to a sandwich. The sandwich is functionally an item storage block, with each slot allowing one item, and it being limited to food. Origins needs to add compat for Sandwichable, checking if the item is a sandwich and contains meat to prevent you from eating it if you are vegetarian. One thing I'd like to know is if Origins classifies whether an item is meat through a tag (like #planks or #piglin_loved) or through something like nbt. If it's nbt I can fix it completely on my end. Otherwise, Origins needs to add a case for eating specifically for this mod.

**Comment by FoundationGames** [comment]
This is going to be closed since there's not really a way I can "fix" this.
