### ISSUE TITLE
feature request/change... salt

### ISSUE THREAD

**Issue by milkev** [FoundationGames/Sandwichable#58]
i dont know if you plan to change the way to obtain salt in 1.2, but here's my thoughts on salt.

1: its to hard to obtain. especially if you are playing with mods such as Terrestria or All the Biomes you'll go.  Oceans, and thus beaches, are increasingly rarer the more types of biomes there are. It may not be a problem in vanilla though.

2: the ores... only spawn in beaches/oceans? I don't know if you are trying to be realistic, but if you are, I'd like to note that salt does have deposits underground... IE; an ore that spawns everywhere would be great, even if its a little rare.

3: alternative to #2, but less realistic. make salt ores spawn in rivers as well, making it more accessible in modded playthroughs.

4: the desalinator!... why does it require redstone? is a piece of coal not good enough? while redstone isnt typically used much in vanilla, especially in the quantities obtained, there are many mods that realistically make use of it (ie: for machines), and some require it in large quantities. If you plan on using these mods the desalinator is essentially cut from use due to it requiring redstone for some unknown reason. It also has to be in a ocean/beach biome?... perhaps make the recipe require things from an ocean monuement, or whatever, but why do i have to be restricted from building away from a beach/ocean biome if I plan to use the desalinator? (which i dont with the way it currently functions)

**Comment by FoundationGames** [comment]
Currently, the purpose of the desalinator is to extract salt from ocean water. There is no salt in freshwater, which is the reason why it doesn't work in a river or pond. As for fuel, I chose redstone because it gives a use to the piles of redstone sitting in your chests used for nothing. In the next update, I will be changing fuel times so you won't need to use as much redstone as you have to now. And after some survival testing, I too have found it too difficult to obtain salt and for little reward, so I think I may add "salt ponds" in 1.2 which work with desalinators too. I could also make desalinators work with tech reborn energy as well.

**Comment by milkev** [comment]
an option to use energy from tech mods would be great!

**Comment by saltyseadoggo** [comment]
I would also love to see Desalinators use energy from Tech Reborn. I love these little cross-compatibility features in mods.~

**Comment by FoundationGames** [comment]
This is going to be partially fixed - Salt will now be obtainable in salt ponds in 1.1.3. Tech reborn energy support will have to wait, however.

**Comment by FoundationGames** [comment]
I'm just closing any issues labeled Fixed in Development so I can work on fixing open issues.
