### ISSUE TITLE
[Request] Option to either remove or edit salt pond generation

### ISSUE THREAD

**Issue by CannibalKon** [FoundationGames/Sandwichable#88]
Add an option in the config to define the biomes salt ponds can spawn in/ or allow the config to let us remove generation of ponds/ or simply allow us to change the generation weight like with shrubs and salty sand ore gen.

**Problem or Reasoning**
As someone who is trying to minimize duplicate items and stuff, as well as work on minimizing land generation issues (due to how salt ponds spawn, they tend to look ugly more than fit in (and that is fine, not the point of the request)) Having this option would allow people to at least shut off generating these things (since salt can generate outside these as well, AND croptopia's salt can be used in place of it).

**How it will work**
Least amount of work (I assume, not a mod developer myself) would probably just to be giving us the same generation options as shrubs and salty sand, but honestly, even just a value to shut off the salt pond generation would be great.

**Comment by FoundationGames** [comment]
Firstly, I'm thinking of removing most of the other worldgen config values.

World Gen is completely driven by json in datapacks, so as a modpack maker you have full liberty to do whatever you want with generated features. Having the config options is incredibly redundant in my opinion and has even caused issues in the past with config registry times. 

However the one thing that isn't feasible to edit with datapacks are the biomes that features spawn in, since you'd have to overwrite the original biome json. This will be left configurable.

**Comment by CannibalKon** [comment]
That's good to know, as I don't entirely understand datapacks yet, trying to shift from my days of 1.7 and 1.12, anywhere I could look to learn how to handle datapacks to help me modify that generation feature?

I appreciate the quick reply! Completely understand where you're coming from, but I definitely see the merit of having salt ponds strictly in deserts and at the bottom of oceans so it would be cool to see that made configurable!

**Comment by FoundationGames** [comment]
There are a few Minecraft Wiki articles on how to configure _vanilla_ generated features. I'd recommend you look into those first.

As of Sandwichable's, I have not documented the feature configuration format anywhere (I'd like to do so if this becomes a popular request) although you could certainly take a look at the code.

**Comment by CannibalKon** [comment]
Okay so I have been looking, and I can see how datapacks are used for the data folder and how I can edit recipes and stuff, but I don't see how to interact with your code, like the .class files.

I apologize if this is veering off of a github feature request too far, but would I need to learn how to edit .class stuff in the datapack?

EDIT: Basically, I can't find where the salt pool is generated anywhere other than /class files.

**Comment by FoundationGames** [comment]
Firstly, all my source code is on this page in the `Code` tab so I don't know why you're looking through compiled class files. Secondly, I suggested you go and look up how to customize vanilla worldgen with datapacks, so that you could understand how modifying worldgen with datapacks works. This thread is getting somewhat off topic, I have a discord server you can join if you'd like to discuss further (see mod page on curseforge/modrinth)

**Comment by FoundationGames** [comment]
Added in 1.2-rc1, changing weight/biomes is yet to be implemented but can be disabled
